APPLICATION_SETTINGS:
  - weight_path: "weights/WEIGHT_PATH_HERE.pth" # VIT-fast-fine-tuning 레포지토리를 활용하여 학습시킨 Weight의 경로를 넣어주세요.
  - config_path: "weights/TTS_CONFIG_JSON_FILE.json" # VIT-fast-fine-tuning 레포지토리에서 목소리를 학습시킬 때 나온 config 파일의 경로를 적어주세요.
  - font_path: "font/FONT_FILE.ttf" # 사용할 폰트의 폰트 파일 경로를 선택합니다.
  - lang_delimiter: "\n" # 원문과 번역문을 구분하는 구별자를 선택합니다 (기본값 : 줄바꿈 문자)
  - print_tts_text: False # TTS에서 나온 원문 메세지를 UI 상단에 출력하려면 True로 변경해주세요.

API_SETTINGS:
  - openai_api_key: "" # GPT Assistants API 키를 적어주세요.
  - openai_assistant_key: "" # Asisstants Key를 적어주세요.

EMOTION_SETTINGS: # 11개의 감정을 지원합니다. 각 감정이 인식 되었을때 출력될 이미지의 경로를 각각 입력해주세요.
  - default_img_path: "img/default.jpg" # 기본 이미지는 감정 인식을 꺼도 필요합니다. 설정해주세요.
  - enabled: False # Enable하려면 MeCab과 mlask를 설치하세요.
  - yasu_img_path: "img/yasu.jpg" # 평온한
  - yorokobi_img_path: "img/yorokobi.jpg" # 즐거운
  - suki_img_path: "img/suki.jpg" # 좋아하는
  - iya_img_path: "img/iyaa.jpg" # 싫어하는
  - takaburi_img_path: "img/takaburi.jpg" # 신난
  - odoroki_img_path: "img/odoroki.jpg" # 놀란
  - haji_img_path: "img/haji.jpg" # 부끄러운
  - aware_img_path: "img/aware.jpg" # 가여운
  - ikari_img_path: "img/ikari.jpg" # 화난
  - kowa_img_path: "img/kowa.jpg" # 무서운

CHARACTER_SETTINGS:
  - character_name: "horo, the wise wolf" # 캐릭터 이름을 설정해주세요.
  - where_character_from: "Spice and Wolf" # 캐릭터가 등장한 작품 명을 적어주세요.
  - character_thinking_text: " is thinking" # API로부터 데이터를 불러오고, TTS 모델을 실행할때 출력될 메세지를 적어주세요.

DISCORD_SETTINGS:
  - bot_token: "" # 디스코드 봇으로 실행하고 싶으면 봇 토큰을 설정해주세요.
  - command_prefix: "!" # 커맨드 접두사를 적어주세요.
  - command: "speak" # 커맨드를 적어주세요 (기본 설정으로는 !speak [메세지] 가 됩니다.)
